# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' pg
# pg ip: 172.18.0.2

version: '3.1'
services:

  db:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
    - 5432:5432

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 80:80
    depends_on:
      - db