# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' pg

version: '3.1'
services:

  db:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: gavr
      POSTGRES_PASSWORD: mysecretpassword

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - 80:80
    depends_on:
      - db